<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDlccfqu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDlccfqu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDlccfqu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDlccfqu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDlccfqu\appDevDebugProjectContainer([
    'container.build_hash' => 'Dlccfqu',
    'container.build_id' => '363dcf3f',
    'container.build_time' => 1607366281,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDlccfqu');
