<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZpblugo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZpblugo/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZpblugo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZpblugo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZpblugo\appProdProjectContainer([
    'container.build_hash' => 'Zpblugo',
    'container.build_id' => '4da25964',
    'container.build_time' => 1607022632,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZpblugo');
